-- SHOW DATABASE DB_NOTAS
CREATE DATABASE 'DB_NOTAS';

-- SHOW TABLE FORNECEDOR
CREATE TABLE FORNECEDOR (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(45) NOT NULL,
  NOME_FANTASIA VARCHAR(45),
  UNIQUE(RAZAO_SOCIAL)
);

