-- START TRANSACTION
START_TRANSACTION;

-- SHOW CREATE DATABASE DB_NOTAS
CREATE DATABASE 'DB_NOTAS';

-- USE DB_NOTA
USE DB_NOTA;

-- SHOW CREATE TABLE FORNECEDOR
CREATE TABLE 'FORNECEDOR' (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  TELEFONE_CASA VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
  TELEFONE_CELULAR VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
  TELEFONE_COMERCIAL VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
  UNIQUE(RAZAO_SOCIAL),
  UNIQUE(EMAIL)
);

-- SHOW CREATE TABLE NOTA
CREATE TABLE 'NOTA' (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FORNECEDOR INT UNSIGNED NOT NULL, -- FK
  DATA_CADASTRO DATE NOT NULL,
  VALOR DEC(11,2) DEFAULT 0.00,
  PARCELAS INT UNSIGNED DEFAULT 1,
  STATUS_NOTA INT UNSIGNED NOT NULL, -- FK
  OBSERVACAO VARCHAR(255) DEFAULT NULL,
  CONSTRAINT 'FK_FORNECEDOR_NOTA' FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDOR (ID),
  CONSTRAINT '' FOREIGN KEY() REFERENCES ()
);

-- SHOW CREATE TABLE PARCELA
CREATE TABLE 'PARCELA' (
  ID_NOTA INT UNSIGNED NOT NULL, -- FK
  NUMERO_PARCELA INT UNSIGNED NOT NULL,
  DATA_VENCIMENTO DATE DEFAULT NULL,
  VALOR DEC(11,2) NOT NULL,
  STATUS_PARCELA,
  CONSTRAINT 'PK_ID_NOTA_PARCELA' PRIMARY KEY(ID_NOTA, NUMERO_PARCELA)
);

-- COMMIT
COMMIT;
