-- SHOW DATABASE DB_NOTAS
CREATE DATABASE 'DB_NOTAS';

-- SHOW TABLE FORNECEDOR
CREATE TABLE 'FORNECEDOR' (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RAZAO_SOCIAL VARCHAR(45) NOT NULL,
  NOME_FANTASIA VARCHAR(45),
  UNIQUE(RAZAO_SOCIAL)
);

-- SHOW TABLE NOTA
CREATE TABLE 'NOTA' (
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FORNECEDOR INT UNSIGNED NOT NULL,
  VALOR DEC(11,2),
  PARCELAS INT UNSIGNED,
  STATUS_NOTA INT UNSIGNED NOT NULL,
  
);
