START_TRANSACTION;

CREATE DATABASE 'PATRIMONIO';

USE PATRIMONIO;

CREATE TABLE 'ANDAR' (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ANDAR VARCHAR(45) NOT NULL,
    UNIQUE(ANDAR)
);

CREATE TABLE 'SALA' (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SALA VARCHAR(255) NOT NULL,
    ANDAR INT UNSIGNED NOT NULL,
);

CREATE TABLE 'BEM' (
    --
);

COMMIT;
