START_TRANSACTION;

CREATE DATABASE 'PATRIMONIO';

USE PATRIMONIO;

CREATE TABLE 'ANDAR' (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ANDAR VARCHAR(45) NOT NULL,
    UNIQUE(ANDAR)
);

CREATE TABLE 'SALA' (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SALA VARCHAR(255) NOT NULL,
    ANDAR INT(11) UNSIGNED NOT NULL,
    CONSTRAINT 'FK_ANDAR_SALA' FOREIGN KEY (ANDAR) REFERENCES ANDAR(ID),
    UNIQUE(SALA)
);

CREATE TABLE 'BEM' (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SAPIENS VARCHAR(13) NOT NULL,
    BEM VARCHAR(255) NOT NULL,
    UNIQUE(SAPIENS)
);

CREATE TABLE 'TOMBAMENTO' (
    ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLAQUETA INT(7) UNSIGNED NOT NULL ZEROFILL,
    BEM VARCHAR(13) NOT NULL,
    SALA INT(11) UNSIGNED NOT NULL,
    CONSTRAINT 'FK_BEM_TOMBAMENTO' FOREIGN KEY(BEM) REFERENCES BEM(ID),
    CONSTRAINT 'FK_SALA_TOMBAMENTO' FOREIGN KEY(SALA) REFERENCES SALA(ID),
    UNIQUE(PLAQUETA),
    UNIQUE(BEM)
);

COMMIT;
