START_TRANSACTION;

CREATE DATABASE 'PATRIMONIO';

USE PATRIMONIO;

CREATE TABLE 'FORNECEDOR' (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL,
    TELEFONE_CASA VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
    TELEFONE_CELULAR VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
    TELEFONE_COMERCIAL VARCHAR(10) DEFAULT NULL, -- EX: 1122223333
    OBSERVACAO VARCHAR(255) DEFAULT NULL,
    UNIQUE(RAZAO_SOCIAL),
    UNIQUE(EMAIL)
);

COMMIT;
